services:
  
  db:
    image: mysql:8.0
    container_name: autofleet_db
    restart: always
    environment:
      MYSQL_DATABASE: autofleet
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306" 
    volumes:
      - db_data:/var/lib/mysql

  dbgate:
    image: dbgate/dbgate
    container_name: autofleet_dbgate
    restart: always
    ports:
      - "8081:3000" 
    depends_on:
      - db

  # Aplicația de Java
  backend:
    build: 
      context: ./backend
    container_name: autofleet_backend
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/autofleet?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_AI_OPENAI_API_KEY=sk-cheie-falsa-pentru-teste-momentan

  
  frontend:
    build: 
      context: ./frontend
    container_name: autofleet_frontend
    restart: on-failure
    ports:
      - "5173:5173" 
    depends_on:
      - backend

volumes:
  db_data: